# TODO: Fill it properly for the current providers
providers:
    github:
        extensions:
            build-signer-digest: job_workflow_sha
            source-repository-digest: sha
            source-repository-ref: ref
            source-repository-identifier: repository_id
            run-invocation-uri: "{{.url}}/{{.repository}}/actions/runs/{{.run_id}}/"
        uris:
            - "{{.url}}/{{.job_workflow_ref}}"
        defaults:
            url: https://github.com
    gitlab:
        extensions:
            build-signer-digest: ci_config_sha
            source-repository-digest: sha
            source-repository-ref: ref
            source-repository-identifier: project_id
            run-invocation-uri: "{{.url}}/{{.project_path}}/-/jobs/{{.job_id}}"
        uris:
            - ci_config_ref_uri
        defaults:
            url: https://gitlab.com
    codefresh:
        extensions:
            build-signer-digest: build/{{.workflow_id}}
            runner-environment: runner_environment
            source-repository-uri: scm_repo_url
            source-repository-ref: scm_ref
            build-config-uri: api/pipelines/{{.pipeline_id}}
            run-invocation-uri: build/{{.workflow_id}}
        uris:
            - "{{.platform_url}}/{{.account_name}}/{{.pipeline_name}}:{{.account_id}}/{{.pipeline_id}}"
        defaults:
            platform_url: https://g.codefresh.io
