#
# Copyright 2023 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI-Container-Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    if: github.repository == 'javanlacerda/fulcio'
    env:
      GH_TOKEN: ${{ github.token }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0

      # TODO: uncomment when we bump to go1.22 in go.mod
      # - name: Extract version of Go to use
      #   run: echo "GOVERSION=$(cat Dockerfile|grep golang | awk ' { print $2 } ' | cut -d '@' -f 1 | cut -d ':' -f 2 | uniq)" >> $GITHUB_ENV

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22'
          check-latest: true

      - name: deps
        run: sudo apt-get update && sudo apt-get install -yq libpcsclite-dev

      - uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037 # v0.7


      - name: Formatted label for breaking change
        id: breaking_change
        run: |
          # Get the pull request number associated with the current commit and the 'breaking-change' label
          BRANCH_NUMBER=$(gh pr list --state all --search "sha:$GITHUB_SHA" | awk '{print $1}')
          echo "Branch Number: $BRANCH_NUMBER" 

          # Check if a pull request number was found
          if [ -n "$BRANCH_NUMBER" ]; then
            FORMATED_LABEL="FORMATED_LABEL=--image-label breaking-change=true"
          else
            FORMATED_LABEL="FORMATED_LABEL=" >> $GITHUB_OUTPUT 
          fi
          echo $FORMATED_LABEL >> $GITHUB_OUTPUT

      - name: container
        run: |
          echo "Formated Label: ${{ steps.breaking_change.outputs.FORMATED_LABEL }}"
          KO_PREFIX=gcr.io/projectsigstore/fulcio/ci/fulcio FORMATED_LABEL=${{ steps.breaking_change.outputs.FORMATED_LABEL }} make sign-keyless-ci
