#
# Copyright 2023 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI-Container-Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    if: github.repository == 'sigstore/fulcio'

    permissions:
      id-token: write
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0

      # TODO: uncomment when we bump to go1.22 in go.mod
      # - name: Extract version of Go to use
      #   run: echo "GOVERSION=$(cat Dockerfile|grep golang | awk ' { print $2 } ' | cut -d '@' -f 1 | cut -d ':' -f 2 | uniq)" >> $GITHUB_ENV

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22'
          check-latest: true

      - name: deps
        run: sudo apt-get update && sudo apt-get install -yq libpcsclite-dev

      - uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037 # v0.7

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d # v2.1.5
        with:
          workload_identity_provider: 'projects/498091336538/locations/global/workloadIdentityPools/githubactions/providers/sigstore-fulcio'
          service_account: 'github-actions-fulcio@projectsigstore.iam.gserviceaccount.com'

      - name: creds
        run: gcloud auth configure-docker --quiet

      - name: Formatted labels
        id: labels
        run: |
          FORMATED_LABELS="--image-label commit-hash=$GITHUB_SHA"

          BRANCH_NUMBER=$(gh pr list --state all --search "sha:$GITHUB_SHA" --label "breaking-change" | awk '{print $1}')
          echo "Branch Number: $BRANCH_NUMBER" 

          # Check if a pull request number was found
          if [ -n "$BRANCH_NUMBER" ]; then
            FORMATED_LABELS+=" --image-label breaking-change=true"
          fi
          echo "FORMATED_LABELS='$FORMATED_LABELS'" >> $GITHUB_OUTPUT

      - name: container
        run: |
          echo "Formated Label: ${{ steps.labels.outputs.FORMATED_LABELS }}"
          KO_PREFIX=gcr.io/projectsigstore/fulcio/ci/fulcio FORMATED_LABEL=${{ steps.labels.outputs.FORMATED_LABELS }} make sign-keyless-ci
